global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      # We reference the cAdvisor service by its container name within the docker network
      - targets: ['cadvisor:8080']